services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    container_name: rabbitmq
    restart: unless-stopped

    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_USER=root
      - RABBITMQ_PASS=root

    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"] # Tried many of these checks and none work so rely on app restarts
      interval: 10s
      timeout: 5s
      retries: 3

    ports:
      - ${SUBMITTED_JOKES_CONTAINER_PORT}:${SUBMITTED_JOKES_PORT}
      - ${RMQ_ADMIN_CONTAINER_PORT}:${RMQ_ADMIN_PORT}

    #volumes:
    #  - rabbit-vol:/var/lib/rabbitmq # Where to store the queued data

  submit:
    image: alsampds.azurecr.io/submit
    pull_policy: always # Attempt to always pull latest image. Lazy if not using versioning. And slow as up will always pull
    build:
      context: ./submit
    container_name: submit-cont
    restart: always
    env_file:
      - .env
    # restart: unless-stopped  # If it stops and I didnt' stop it then have another go
    depends_on:
      - rabbitmq
    volumes:
      - types:/var/lib/types

    ports:
      - ${SUBMIT_CONTAINER_PORT}:${SUBMIT_PORT}
volumes:
  types:
    driver: local
